### ISSUE TITLE
Incompatibility between java and python release - update dependency in abba python 

### ISSUE THREAD

**Issue by chongtianyifa** [BIOP/abba_python#19]
* ABBA Python version:  0.5.0
* Python version: 3.10.13
* Operating System: 3.10.13

### Description

I was trying to transform coordinates in ABBA_python using a saved state file. It worked with an old state file A but failed with a recent state file B, although ImageJ and ABBA were not upgraded. ABBA can load the state 
file B successfully, while ABBA_python can only add the first image and showed error 'Could not load state:Please check the stack trace'. I resaved the loaded A state as A1 in ABBA, and ABBA_python cannot load this new state file.

Here is the code I ran:

`aligner = Abba('Adult Mouse Brain - Allen Brain Atlas V3p1')
aligner.state_load(state_file)  
allSlices = aligner.mp.getSlices()`
allSlices should be a list with the length of the number of images and it is a single element if loading falsely now.

Is there a way to fix this issue? I think the transformation was complete as ABBA can load the state correctly.

Attached are A, A1 state files and the errors.
[state file.zip](https://github.com/user-attachments/files/16258922/state.file.zip)
[error output.txt](https://github.com/user-attachments/files/16258928/error.output.txt)

**Comment by chongtianyifa** [comment]
Thank you for the quick response!
I cannot fix it following your guide. Specifically, I am not sue which file to edit. When I open A_bdv_view.json, I did not find InvertibleWrapped2DTransformAs3D. When I open A.abba in windows Notepad, the text was not correctly shown. Could you explain this more?

**Comment by NicoKiaru** [comment]
The abba file is in reality a zip file. So:

Change the extension of the file state.abba to state.zip. Unzip it, change the text in the state.json file, then rezip the whole thing and try to open it.

Let me know how that goes.

**Comment by chongtianyifa** [comment]
Thank you! The issue is fixed!
